export const stock_symbols = [
    { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy' },
    { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
    { symbol: 'EOG', name: 'EOG Resources, Inc.', sector: 'Energy' },
    { symbol: 'PTR', name: 'PetroChina Company Limited', sector: 'Energy' },
    { symbol: 'TOT', name: 'TotalEnergies SE', sector: 'Energy' },
    { symbol: 'BP', name: 'BP p.l.c.', sector: 'Energy' },
    { symbol: 'ENB', name: 'Enbridge Inc.', sector: 'Energy' },
    { symbol: 'SLB', name: 'Schlumberger Limited', sector: 'Energy' },
    { symbol: 'KMI', name: 'Kinder Morgan, Inc.', sector: 'Energy' },
    { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
    { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Tech' },
    { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Tech' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Tech' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Tech' },
    { symbol: 'FB', name: 'Meta Platforms, Inc.', sector: 'Tech' },
    { symbol: 'TSLA', name: 'Tesla, Inc.', sector: 'Tech' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Tech' },
    { symbol: 'INTC', name: 'Intel Corporation', sector: 'Tech' },
    { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Tech' },
    { symbol: 'CRM', name: 'salesforce.com, inc.', sector: 'Tech' },
    { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Food' },
    { symbol: 'PEP', name: 'PepsiCo, Inc.', sector: 'Food' },
    { symbol: 'MCD', name: "McDonald's Corporation", sector: 'Food' },
    { symbol: 'NKE', name: 'NIKE, Inc.', sector: 'Food' },
    { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Food' },
    { symbol: 'MDLZ', name: 'Mondelez International, Inc.', sector: 'Food' },
    { symbol: 'KHC', name: 'The Kraft Heinz Company', sector: 'Food' },
    { symbol: 'YUM', name: 'Yum! Brands, Inc.', sector: 'Food' },
    { symbol: 'DRI', name: 'Darden Restaurants, Inc.', sector: 'Food' },
    { symbol: 'GIS', name: 'General Mills, Inc.', sector: 'Food' },
    { symbol: 'NEE', name: 'NextEra Energy, Inc.', sector: 'Utilities' },
    { symbol: 'DUK', name: 'Duke Energy Corporation', sector: 'Utilities' },
    { symbol: 'SO', name: 'The Southern Company', sector: 'Utilities' },
    { symbol: 'D', name: 'Dominion Energy, Inc.', sector: 'Utilities' },
    { symbol: 'EXC', name: 'Exelon Corporation', sector: 'Utilities' },
    { symbol: 'AEP', name: 'American Electric Power Company, Inc.', sector: 'Utilities' },
    { symbol: 'SRE', name: 'Sempra Energy', sector: 'Utilities' },
    { symbol: 'PEG', name: 'Public Service Enterprise Group Incorporated', sector: 'Utilities' },
    { symbol: 'XEL', name: 'Xcel Energy Inc.', sector: 'Utilities' },
    { symbol: 'WEC', name: 'WEC Energy Group, Inc.', sector: 'Utilities' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
    { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
    { symbol: 'UNH', name: 'UnitedHealth Group Incorporated', sector: 'Healthcare' },
    { symbol: 'MRK', name: 'Merck & Co., Inc.', sector: 'Healthcare' },
    { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
    { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare' },
    { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
    { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
    { symbol: 'GILD', name: 'Gilead Sciences, Inc.', sector: 'Healthcare' },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb Company', sector: 'Healthcare' },
    { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financials' },
    { symbol: 'BAC', name: 'Bank of America Corporation', sector: 'Financials' },
    { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Financials' },
    { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financials' },
    { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.', sector: 'Financials' },
    { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials' },
    { symbol: 'AXP', name: 'American Express Company', sector: 'Financials' },
    { symbol: 'BLK', name: 'BlackRock, Inc.', sector: 'Financials' },
    { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financials' },
    { symbol: 'PNC', name: 'The PNC Financial Services Group, Inc.', sector: 'Financials' }
];
